version: '3.9'

services:

  centic-api:
    build:
      context: .
      dockerfile: ./Dockerfile
#    image: hoangthanhlamm/centic-api:v1.1.0-release
    container_name: centic-api
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/centic-api
    environment:
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis/0
    env_file:
      - .env

  redis:
    image: redis:latest
    command: >
      --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always
